config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', to: 'pages#dashboard'
  get 'home/index'
  devise_for :users
  root to: "cars#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :cars do
    resources :users, only: %i[new create]
    resources :orders, only: %i[create]
  end

  resources :orders, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :orders, dependent: :destroy

  has_many_attached :photos
  monetize :price_cents

  validates :brand, presence: true
  validates :year, presence: true, numericality: { only_integer: true }
  validates :model, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :description, presence: true

  scope :available, -> { where(sold: false) }

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :brand, :model, :year, :description],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cars, dependent: :destroy
  has_many :orders, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  # Display a list of cars with optional brand filtering
  def index
    @cars = Car.available
    if params[:search].present? && params[:search][:query] != ''
      @cars = Car.available.global_search(params[:search][:query])
    end
  end

  # Show details about a specific car
  def show
    @car = Car.find(params[:id])
    @order = Order.new

    # Fetch additional cars for display. It will only display 3 cars
    # @cars = Car.where.not(id: @car.id).limit(3)
    @cars = Car.available.where.not(id: @car.id).limit(3)
  end

  # display the form to create a new car
  def new
    @car = Car.new
  end

  # Create a new car and associate it with the current user
  def create
    @car = Car.new(car_params)
    @user = User.find(current_user.id)
    @car.user_id = @user.id
    if @car.save
      redirect_to @car, notice: 'Car was successfully created.'
    else
      ## render the new car form again for correction of typos and trigger authenticity token error
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id]) # find the car to update
    @car.update(car_params)
    redirect_to car_path(@car)
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to root_path
  end

  private

  # Define the allowed parameters for creating a car
  def car_params
    params.require(:car).permit(:brand, :year, :model, :price_cents, :description, photos: [])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_user.orders
  end

  def show
    # @order = Order.find(params[:id])
    @order = current_user.orders.find(params[:id])
    @car = @order.car # car associated with the order we are showing
  end

  def create
    @car = Car.find(params[:car_id])
    @car.sold = true
    @car.save
    @order = Order.new(car: @car, user: current_user)
    if @order.save!
      redirect_to order_path(@order.id)
    else
      render 'cars/show'
    end
    # Order.create(car_id: params[:car_id], user_id: current_user.id)
    # redirect_to car_path(params[:car_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
    @cars = current_user.cars
    @orders = current_user.orders
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/edit.html.erb
<h1>Update Car's information</h1>

<%= simple_form_for(@car) do |f| %>
  <%= f.input :brand %>
  <%= f.input :year %>
  <%= f.input :model %>
  <%= f.input :price %>
  <%= f.input :description %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/cars/index.html.erb
<div class="banner mt-2">
  <div class="banner-title"><h1>CarTradeHub</h1></div>
</div>

<!-- Car Cards Section -->
<div class="container">
  <div class="row">
    <% @cars.each do |car| %>
      <div class="col-md-4">
        <div class="card mt-4 car-card">
          <%= link_to car_path(car.id) do %> <!-- Wrap the entire card content in a link -->
            <% if car.photos.present? %>
              <%= cl_image_tag car.photos.first.key, class: "card-img-top", alt: "Car Photo" %>
            <% else %>
              <!-- Use the default photo when no photos are available -->
              <%= image_tag "usedcar_hub.jpg", class: "card-img-top", alt: "Default Car Photo" %>
            <% end %>
            <div class="card-body card-content"> <!-- Add a class to the card content -->
              <h4 class="card-title"><strong><%= car.brand %></strong></h4>
              <h5 class="card-text"><%= "#{car.year} #{car.model}" %></h5>
              <p class="card-text" id="price--num">€<%= humanized_money car.price %></p>
              <p class="delete-edit-btn">
                <% if user_signed_in? && current_user == car.user %>
                  <%= link_to "Edit", edit_car_path(car.id), class: "btn btn-outline-info link-btn m-1" %>
                  <%= link_to "Delete", car_path(car.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-outline-danger link-btn" %>
                <% end %>
              </p>
            </div>
          <% end %> <!-- Close the link here -->
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cars/new.html.erb
<div class="container">
  <h1>Add a car</h1>

  <%= simple_form_for(@car) do |f| %>
    <% brand_names = %w[
Alfa-Romeo
Aston-Martin
Audi
Bentley
BMW
Bugatti
Cadillac
Chevrolet
Chrysler
Dodge
Ferrari
Ford
GMC
Honda
Hyundai
Jaguar
Jeep
Kia
Lamborghini
Land-Rover
Lexus
Maserati
Mazda
Mercedes-Benz
Nissan
Porsche
Rolls-Royce
Subaru
Toyota] %>
    <%= f.input :brand, collection: brand_names %>
    <%= f.input :year %>
    <%= f.input :model %>
    <%= f.input :price_cents %>
    <%= f.input :description %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/cars/show.html.erb
<div class="container">
  <div class="row justify-content-center">

    <!-- Car Image Carousel Column (Left) -->
    <div class="col-md-9 my-1">
      <div id="carImageCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <!-- Loop through car photos and create carousel items -->
          <% @car.photos.each_with_index do |photo, index| %>
            <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
              <!-- Display car image using Cloudinary's 'cl_image_tag' helper -->
                <%= cl_image_tag photo.key, class: "carousel-image" %>
              </div>
          <% end %>
        </div>

        <!-- Carousel navigation button (Previous) -->
        <button class="carousel-control-prev" type="button" data-bs-target="#carImageCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <!-- Carousel navigation button (Next) -->
        <button class="carousel-control-next" type="button" data-bs-target="#carImageCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>

      <!-- Car Description -->
      <div class="mt-3">
        <p class="card--description-text">
          <h5 class="custom-h5">Description:</h5>
        </p>
        <p class="card--description-text mb-0">
          <%= @car.description %>
        </p>
      </div>
    </div>

    <!-- Car Details Column (Right) -->
    <div class="col-md-3 my-1 border-0 text-center">
      <div class="card card--container square-content  box-shadow car-info-plate">

        <!-- Car Details Content -->
        <div class="card-body mx-5 mt-4">

          <!-- Car Title (Brand) -->
          <h2 class="show-card-title mb-3">
          <!-- Display car brand -->
          <%= @car.brand %>
          </h2>

          <!-- Car Brand -->
          <div class="show-card-text mb-0">
            <strong>Model</strong>
            <p><%= @car.model %></p>

          <!-- Car Year -->
            <strong>Year</strong>
            <p><%= @car.year %></p>
          </div>

          <!-- Car Price -->
          <p class="show-card--price-text mb-4">
          <strong><span id="price--num">€<%= humanized_money @car.price %></span></strong>
          </p>

          <!-- Only show the buy button if the user is not the car owner -->
          <% if user_signed_in? && current_user != @car.user %>
            <%= simple_form_for [@car, @order] do |f| %>
            <%= f.submit "Buy Now", class: "btn btn-primary" %>
            <% end %>
          <% else %>
            <p class="delete-edit-btn">
              <%= link_to "Edit", edit_car_path(@car.id), class: "btn btn-outline-info link-btn m-1" %>
              <%= link_to "Delete", car_path(@car.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-outline-danger link-btn" %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Split text between car info and car cards -->
<div class="col-md-12 text-center my-0 mb-0 mt-5">
  <h3 class="custom-h3">Cars in inventory:</h3>
</div>

<!-- Car Cards Section (same code from index but modified the .each method to display 3 cards) -->
<div class="container">
  <div class="row">
    <% @cars.last(3).each do |car| %>
      <div class="col-md-4">
        <div class="card mt-4 car-card">
          <%= link_to car_path(car.id) do %> <!-- Wrap the entire card content in a link -->
            <% if car.photos.present? %>
              <%= cl_image_tag car.photos.first.key, class: "card-img-top", alt: "Car Photo" %>
            <% else %>
              <!-- Use the default photo when no photos are available -->
              <%= image_tag "usedcar_hub.jpg", class: "card-img-top", alt: "Default Car Photo" %>
            <% end %>
            <div class="card-body card-content"> <!-- Add a class to the card content -->
              <h4 class="card-title"><strong><%= car.brand %></strong></h4>
              <h5 class="card-text"><%= "#{car.year} #{car.model}" %></h5>
              <p class="card-text" id="price--num">€<%= humanized_money car.price %></p>
              <p class="delete-edit-btn">
                <% if user_signed_in? && current_user == car.user %>
                  <%= link_to "Edit", edit_car_path(car.id), class: "btn btn-outline-info link-btn m-1" %>
                  <%= link_to "Delete", car_path(car.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-outline-danger link-btn" %>
                <% end %>
              </p>
            </div>
          <% end %> <!-- Close the link here -->
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarTradeHub</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.4.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= render "shared/navbar" %>
      <div class="container main">
        <%= yield %>
      </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/orders/index.html.erb
<h2>I am order index</h2>
<%= @orders %>

app/views/orders/show.html.erb
<section class="h-100 h-custom">
  <div class="container py-0 h-100 ">
    <div class="row d-flex justify-content-center align-items-center h-100 ">
      <div class="col-lg-8 col-xl-6">
        <div class="card order--conatiner" >
          <div class="card-body p-5 container--color">
            <h2 class="order--message mb-5 mt-3">Thank you for your order <%= current_user.first_name %>!</h2>
            <p class="lead mb-5 p--blue">Order Details</p>

            <div class="row">
              <div class="col mb-3">
                <p class="small text-muted mb-1"><strong>Date</strong></p>
                <!--date time-->
                <p><%= Time.now.strftime("%d/%m/%Y %T") %></p>
              </div>
              <div class="col mb-3 text-end"> <!-- Align to the right -->
                <p class="small text-muted mb-1"><strong>Order No.</strong></p>

                <!--add order no. with order id for uniqueness-->
                <p><%= @order.id %></p>
              </div>
            </div>

            <div class="mx-n5 px-5 py-4">
              <div class="row">
                <div class="col-md-8 col-lg-9">
                  <p><%= "#{@order.car.year} #{@order.car.brand} #{@order.car.model}" %></p>
                </div>
                <div class="col-md-4 col-lg-3 text-end"> <!-- Align to the right -->
                  <% car_price = @order.car.price - (@order.car.price * 0.19) %>
                  <!--use number_to_currency to display nice price-->
                  <p><%= number_to_currency(car_price, precision: 2, unit: "€", separator: ".") %></p>
                </div>
              </div>
              <div class="row">
                <div class="col-md-8 col-lg-9">
                  <p class="mb-0">Taxes and Fees</p>
                </div>
                <div class="col-md-4 col-lg-3 text-end"> <!-- Align to the right -->
                <!--use number_to_currency to display nice price-->
                  <% tax = @order.car.price * 0.19 %>
                  <p class="mb-0"><%= number_to_currency(tax, precision: 2, unit: "€", separator: ".") %></p>
                </div>
              </div>
            </div>

            <div class="row my-4">
              <div class="col-md-4 offset-md-8 col-lg-3 offset-lg-9 text-end"> <!-- Align to the right -->
                <h5 class="mb-0 p--blue"><strong>Total</strong></h5>
                <% total = (@order.car.price)  %>
                <!--use number_to_currency to display nice price-->
                <p class="lead mb-0" ><strong><%= number_to_currency(total, precision: 2, unit: "€", separator: ".") %></strong></p>
              </div>
            </div>

            <p class="lead mb-4 pb-2 p--blue">Order Status</p>

            <div class="row">
              <div class="col-lg-12">
                <div class="horizontal-timeline" data-controller="delayed-display">
                  <ul class="list-inline items d-flex justify-content-between">
                    <li class="list-inline-item items-list">
                      <!--Order status using stimulus-->
                      <p class="py-0 px-2 rounded p--status " data-delayed-display-target="orderStatus" >Your order is being processed <i class="fa-solid fa-bars-progress fa-spin" style="color: #ffffff;"></i></p>
                    </li>
                  </ul>
                  <!--link to dashboard(app/views/pages/dashboard.html.erb)-->
                  <!--<%= link_to "Your order", dashboard_path %>-->
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/dashboard.html.erb
  <h2>Order History</h2>
  <table class="table mb-5">
    <thead class="thead-light">
      <tr>
        <th scope="col">Order no.</th>
        <th scope="col">Product</th>
        <th scope="col">Price</th>
        <th scope="col">Order Date</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      <!--initialize total_order_price-->
      <% total_order_price = 0 %>
      <% @orders.each do |order| %>
        <tr>
          <th scope="row"><%= order.id %></th>
          <td><%= "#{order.car.year} #{order.car.model}" %></td>
          <td><%= number_to_currency(order.car.price, precision: 2, unit: "€", separator: ".") %></td>
          <td><%= order.created_at.strftime("%d/%m/%Y") %></td>
          <!--If above 40 seconds has passed from the time of order, status will change to "For delivery." -->
          <!--This is for presentation purposes only -->
          <% if Time.now - order.created_at > 40 %>
            <td>For delivery</td>
          <% else %>
            <td>Processing</td>
          <% end %>
        </tr>
        <!--Add the price of each order to total_order_price-->
        <% total_order_price += order.car.price %>
      <% end %>
      <!-- Display the total price row -->
      <tr>
        <!-- colspan="2" helps the total price allign with the "Price column" -->
        <th colspan="2" class="text-right">Total:</th>
        <td><%= number_to_currency(total_order_price, precision: 2, unit: "€", separator: ".") %></td>
      </tr>
    </tbody>
  </table>

  <h2>Sell History</h2>
  <table class="table mb-5">
    <thead class="thead-light">
      <tr>
        <th scope="col">Order no.</th>
        <th scope="col">Product</th>
        <th scope="col">Price</th>
        <th scope="col">Order Date</th>
      </tr>
    </thead>
    <tbody>
      <!--initialize total_order_price-->
      <% total_order_price = 0 %>
      <% @cars.each do |car| %>
        <% if car.sold == true %>
          <tr>
              <th scope="row"><%= car.id%></th>
              <td><%= "#{car.year} #{car.model}" %></td>
              <td><%= number_to_currency(car.price, precision: 2, unit: "€", separator: ".") %></td>
              <td><%= car.created_at.strftime("%d/%m/%Y")%></td>
          </tr>
        <% total_order_price += car.price %>
        <% end %>
      <% end %>
      <tr>
        <!-- colspan="2" helps the total price allign with the "Price column" -->
        <th colspan="2" class="text-right">Total:</th>
        <td><%= number_to_currency(total_order_price, precision: 2, unit: "€", separator: ".") %></td>
      </tr>
    </tbody>
  </table>

  <h2>My Cars</h2>
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">Car no.</th>
        <th scope="col">Product</th>
        <th scope="col">Price</th>
        <th scope="col">Post Date</th>
      </tr>
    </thead>
    <tbody>
      <% @cars.each do |car| %>
        <% if car.sold == false %>
          <tr>
            <th scope="row"><%= car.id %></th>
            <td><%= "#{car.year} #{car.model}" %></td>
            <td><%= number_to_currency(car.price, precision: 2, unit: "€", separator: ".") %></td>
            <td><%= car.created_at.strftime("%d/%m/%Y")%></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_footer.html.erb
<footer class="text-center text-white" style="background-color: #F4F4F4;">
  <!-- Grid container -->
  <div class="container pt-4">
    <!-- Section: Social media -->
    <h5 style="color: black;">Follow us on social media</h5>
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        ><i class="fab fa-linkedin"></i
      ></a>
      <!-- Github -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center text-dark p-3" style="background-color:#F4F4F4;">
    © 2023 Copyright:
    <a class="text-dark" href="/">CarTradeHub</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-usedcar">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <%= image_tag "usedcar_hub.jpg", alt: "usedcar_hub_logo", width: 100 %>
</a>
<div class="d-flex mx-3">
<%= simple_form_for :search, url: root_path, method: :get do |f| %>
  <div class="search-form-control form-group ">
    <input class="form-control string required mx-1" placeholder="Search any car" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn btn-primary">
      <i class="fas fa-search"></i>
    </button>
  </div>
<% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home</a>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <i class="avatar dropdown-toggle fa-solid fa-user fa-lg align-bottom" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Add a car", new_car_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
        <% else %>
          <li class="nav-item dropdown">
            <i class="avatar dropdown-toggle fa-solid fa-user fa-lg align-bottom" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
              <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  </div>
</div>